pull_request_rules:
  - name: Automatic merge for flake-lock updates
    conditions:
      - "head~=update/flake-lock"
      - "author=mksafavi"
      - "status-success=build-machine (t1000)"
      - "status-success=build-machine (t800)"
      - "status-success=build-machine (t70)"
      - "status-success=build-devshell"
    actions:
      merge:
        method: rebase
