name: deploy flake

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - main

jobs:
  deploy-devshell:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_PUSH_TOKEN }}
          skip-push: true
          skip-use: true

      - run: |
          nix build .#devShells.default

      - run: |
          attic push --jobs ${{ vars.ATTIC_JOBS }} ${{ secrets.ATTIC_CACHE }} result

  deploy-machine:
    strategy:
      fail-fast: false
      matrix:
        machine: ["t1000", "t800", "t70"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7

      - name: ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          cache: ${{ secrets.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_PUSH_TOKEN }}
          skip-push: true
          skip-use: true

      - run: |
          nix build .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel

      - run: |
          attic push --jobs ${{ vars.ATTIC_JOBS }} ${{ secrets.ATTIC_CACHE }} result
